const data = {
    products: [
        {
            id: 1,
            profile: '',
            main_img: 'images/image-product-1.jpg',
            img_1: 'images/image-product-1-thumbnail.jpg',
            img_2: 'images/image-product-2-thumbnail.jpg',
            img_3: 'images/image-product-3-thumbnail.jpg',
            img_4: 'images/image-product-4-thumbnail.jpg',
            paragraph: 'lorem granier active Micellear, sneaker company, 125 ml',
            company_name: 'SNEAKER COMPANY',
            title: 'Fall Limited Edition Sneakers',
            description: 'These low-profile sneakers are your perfect casual wear companion. Featuring a durable ruber outer sole, they&apos;ll withstand everything the weather can offer.',
            price: '125.00',
            price_off: '50%',
            price_before: '250',
        },
        {
            id: 2,
            profile: '',
            main_img: '',
            img_1: '',
            img_2: '',
            img_3: '',
            img_4: '',
            paragraph: '',
            company_name: '',
            title: '',
            description: '',
            price: '',
            price_off: '',
            price_before: '',
        },
        {
            id: 3,
            profile: '',
            main_img: '',
            img_1: '',
            img_2: '',
            img_3: '',
            img_4: '',
            paragraph: '',
            company_name: '',
            title: '',
            description: '',
            price: '',
            price_off: '',
            price_before: '',
        },
        {
            id: 4,
            profile: '',
            main_img: '',
            img_1: '',
            img_2: '',
            img_3: '',
            img_4: '',
            paragraph: '',
            company_name: '',
            title: '',
            description: '',
            price: '',
            price_off: '',
            price_before: '',
        },
        {
            id: 5,
            profile: '',
            main_img: '',
            img_1: '',
            img_2: '',
            img_3: '',
            img_4: '',
            paragraph: '',
            company_name: '',
            title: '',
            description: '',
            price: '',
            price_off: '',
            price_before: '',
        },
        {
            id: 6,
            profile: '',
            main_img: '',
            img_1: '',
            img_2: '',
            img_3: '',
            img_4: '',
            paragraph: '',
            company_name: '',
            title: '',
            description: '',
            price: '',
            price_off: '',
            price_before: '',
        },
        {
            id: 7,
            profile: '',
            main_img: '',
            img_1: '',
            img_2: '',
            img_3: '',
            img_4: '',
            paragraph: '',
            company_name: '',
            title: '',
            description: '',
            price: '',
            price_off: '',
            price_before: '',
        },
    ]
};

export default data;