const data = {
    products: [
        {
            id: '1',
            profile: '',
            main_img: '/images/image-product-1.jpg',
            img_1: '/images/image-product-1-thumbnail.jpg',
            img_2: '/images/image-product-2-thumbnail.jpg',
            img_3: '/images/image-product-3-thumbnail.jpg',
            img_4: '/images/image-product-4-thumbnail.jpg',
            paragraph: 'lorem granier active Micellear, sneaker company, 125 ml',
            company_name: 'SNEAKER COMPANY',
            title: 'Fall Limited Edition Sneakers',
            description: 'These low-profile sneakers are your perfect casual wear companion. Featuring a durable ruber outer sole, they&apos;ll withstand everything the weather can offer.',
            price: '125.00',
            price_off: '50%',
            price_before: '250',
        },
        {
            id: '2',
            profile: '',
            main_img: '/images/black/men_black.png',
            img_1: '/images/black/men_black.png',
            img_2: '/images/black/men_black_1.jpeg',
            img_3: '/images/black/men_black_2.jpeg',
            img_4: '/images/black/men_black.png',
            paragraph: 'lorem granier active Micellear, sneaker company, 125 ml',
            company_name: 'SNEAKER COMPANY',
            title: 'High-Performance Tech Kicks',
            description: 'Engineered for peak performance, these sneakers boast cutting-edge technology. From advanced cushioning to responsive soles, they provide the support needed for your most intense workouts.',
            price: '250',
            price_off: '50',
            price_before: '500',
        },
        {
            id: '3',
            profile: '',
            main_img: '/images/whitesneaker/white_1.jpg',
            img_1: '/images/whitesneaker/white_1.jpg',
            img_2: '/images/whitesneaker/white_2.webp',
            img_3: '/images/whitesneaker/white_3.jpeg',
            img_4: '/images/whitesneaker/white_2.webp',
            paragraph: 'lorem granier active Micellear, sneaker company, 125 ml',
            company_name: 'UNDER ARMOUR',
            title: 'Premium Leather Court Shoes',
            description: 'Experience luxury with these court-style sneakers featuring a premium leather finish. They effortlessly blend sophistication with everyday comfort.',
            price: '120',
            price_off: '50',
            price_before: '240',
        },
        {
            id: '4',
            profile: '',
            main_img: '/images/blue_sneaker.jpg',
            img_1: '/images/blue_sneaker.jpg',
            img_2: '/images/blue_sneaker.jpg',
            img_3: '/images/blue_sneaker.jpg',
            img_4: '/images/blue_sneaker.jpg',
            paragraph: 'lorem granier active Micellear, sneaker company, 125 ml',
            company_name: 'REEBOK',
            title: 'Neon Streetwear Trainers',
            description: 'Stand out in the crowd with these vibrant neon sneakers. Perfect for adding a bold and energetic touch to your streetwear ensemble.',
            price: '300',
            price_off: '50',
            price_before: '670',
        },
        {
            id: '5',
            profile: '',
            main_img: '/images/women_pink.jpeg',
            img_1: '/images/women_pink.jpeg',
            img_2: '/images/women_pink.jpeg',
            img_3: '/images/women_pink.jpeg',
            img_4: '/images/women_pink.jpeg',
            paragraph: 'lorem granier active Micellear, sneaker company, 125 ml',
            company_name: 'NEW BALANCE',
            title: 'Lightweight Marathon Racers',
            description: 'Designed for the long run, these sneakers are incredibly lightweight without compromising on durability. Ideal for marathon enthusiasts and daily runners alike.',
            price: '250',
            price_off: '50',
            price_before: '550',
        },
        {
            id: '6',
            profile: '',
            main_img: '/images/sneaker_1.jpg',
            img_1: '/images/sneaker_1.jpg',
            img_2: '/images/sneaker_1.jpg',
            img_3: '/images/sneaker_1.jpg',
            img_4: '/images/sneaker_1.jpg',
            paragraph: 'lorem granier active Micellear, sneaker company, 125 ml',
            company_name: 'SKECHERS',
            title: 'Eco-Friendly Casuals',
            description: 'Make a statement with these environmentally conscious sneakers. Crafted from sustainable materials, they offer both style and a commitment to reducing your carbon footprint.',
            price: '400',
            price_off: '50',
            price_before: '900',
        },
        {
            id: '7',
            profile: '',
            main_img: '/images/sneaker_2.jpeg',
            img_1: '/images/sneaker_2.jpeg',
            img_2: '/images/sneaker_2.jpeg',
            img_3: '/images/sneaker_2.jpeg',
            img_4: '/images/sneaker_2.jpeg',
            paragraph: 'lorem granier active Micellear, sneaker company, 125 ml',
            company_name: 'SNEAKER COMPANY',
            title: 'Minimalist Everyday Sneaks',
            description: 'Embrace simplicity with these minimalist sneakers. A clean design and lightweight construction make them a versatile choice for everyday wear.',
            price: '250',
            price_off: '50',
            price_before: '60',
        },
    ]
};

export default data;